export const partnerCategories = [
  {
    title: "Security",
    logos: [
      { src: "/images/partners&clients/partners/Security/image001.png", alt: "Partner 1" },
      { src: "/images/partners&clients/partners/Security/image003.png", alt: "Partner 3" },
      { src: "/images/partners&clients/partners/Security/image004.png", alt: "Partner 4" },
      { src: "/images/partners&clients/partners/Security/image007.png", alt: "Partner 7" },
      { src: "/images/partners&clients/partners/Security/image008.png", alt: "Partner 8" },
      { src: "/images/partners&clients/partners/Security/image009.png", alt: "Partner 9" },
      { src: "/images/partners&clients/partners/Security/image013.png", alt: "Partner 13" },
      { src: "/images/partners&clients/partners/Security/image014.png", alt: "Partner 14" },
      { src: "/images/partners&clients/partners/Security/image015.png", alt: "Partner 15" },
      { src: "/images/partners&clients/partners/Security/image019.png", alt: "Partner 19" },
      { src: "/images/partners&clients/partners/Security/image020.png", alt: "Partner 20" },
      { src: "/images/partners&clients/partners/Security/image021.png", alt: "Partner 21" },
      { src: "/images/partners&clients/partners/Security/image025.png", alt: "Partner 25" },
      { src: "/images/partners&clients/partners/Security/image026.png", alt: "Partner 26" },
      { src: "/images/partners&clients/partners/Security/image030.png", alt: "Partner 30" },
      { src: "/images/partners&clients/partners/Security/image032.jpg", alt: "Partner 32" },
      { src: "/images/partners&clients/partners/Security/image034.png", alt: "Partner 34" },
      { src: "/images/partners&clients/partners/Security/image036.png", alt: "Partner 36" },
      { src: "/images/partners&clients/partners/Security/image037.png", alt: "Partner 37" },
      { src: "/images/partners&clients/partners/Security/image038.png", alt: "Partner 38" }
    ]
  },
  {
    title: "AV",
    logos: [
      { src: "/images/partners&clients/partners/AV/image001.png", alt: "Partner 1" },
      { src: "/images/partners&clients/partners/AV/image002.png", alt: "Partner 2" },
      { src: "/images/partners&clients/partners/AV/image003.png", alt: "Partner 3" },
      { src: "/images/partners&clients/partners/AV/image007.png", alt: "Partner 7" },
      { src: "/images/partners&clients/partners/AV/image008.png", alt: "Partner 8" },
      { src: "/images/partners&clients/partners/AV/image009.png", alt: "Partner 9" },
      { src: "/images/partners&clients/partners/AV/image013.png", alt: "Partner 13" },
      { src: "/images/partners&clients/partners/AV/image014.png", alt: "Partner 14" },
      { src: "/images/partners&clients/partners/AV/image015.png", alt: "Partner 15" },
      { src: "/images/partners&clients/partners/AV/image019.png", alt: "Partner 19" },
      { src: "/images/partners&clients/partners/AV/image020.png", alt: "Partner 20" },
      { src: "/images/partners&clients/partners/AV/image021.png", alt: "Partner 21" },
      { src: "/images/partners&clients/partners/AV/image025.png", alt: "Partner 25" },
      { src: "/images/partners&clients/partners/AV/image026.png", alt: "Partner 26" },
      { src: "/images/partners&clients/partners/AV/image027.png", alt: "Partner 27" },
      { src: "/images/partners&clients/partners/AV/image031.png", alt: "Partner 31" },
      { src: "/images/partners&clients/partners/AV/image032.png", alt: "Partner 32" },
      { src: "/images/partners&clients/partners/AV/image033.png", alt: "Partner 33" },
      { src: "/images/partners&clients/partners/AV/image037.png", alt: "Partner 37" },
      { src: "/images/partners&clients/partners/AV/image038.png", alt: "Partner 38" },
      { src: "/images/partners&clients/partners/AV/image039.png", alt: "Partner 39" },
      { src: "/images/partners&clients/partners/AV/image043.png", alt: "Partner 43" },
      { src: "/images/partners&clients/partners/AV/image044.png", alt: "Partner 44" },
      { src: "/images/partners&clients/partners/AV/image045.png", alt: "Partner 45" },
      { src: "/images/partners&clients/partners/AV/image049.png", alt: "Partner 49" },
      { src: "/images/partners&clients/partners/AV/image052.png", alt: "Partner 52" },
      { src: "/images/partners&clients/partners/AV/image054.png", alt: "Partner 54" },
      { src: "/images/partners&clients/partners/AV/image055.png", alt: "Partner 55" },
      { src: "/images/partners&clients/partners/AV/image056.png", alt: "Partner 56" },
      { src: "/images/partners&clients/partners/AV/image057.png", alt: "Partner 57" },
      { src: "/images/partners&clients/partners/AV/image061.png", alt: "Partner 61" },
      { src: "/images/partners&clients/partners/AV/image062.png", alt: "Partner 62" },
      { src: "/images/partners&clients/partners/AV/image063.png", alt: "Partner 63" },
      { src: "/images/partners&clients/partners/AV/image067.png", alt: "Partner 67" },
      { src: "/images/partners&clients/partners/AV/image068.png", alt: "Partner 68" }
    ]
  },
  {
    title: "Network & communication",
    logos: [
      { src: "/images/partners&clients/partners/Network & communication/image002.png", alt: "Partner 2" },
      { src: "/images/partners&clients/partners/Network & communication/image003.png", alt: "Partner 3" },
      { src: "/images/partners&clients/partners/Network & communication/image004.png", alt: "Partner 4" },
      { src: "/images/partners&clients/partners/Network & communication/image008.png", alt: "Partner 8" },
      { src: "/images/partners&clients/partners/Network & communication/image009.png", alt: "Partner 9" },
      { src: "/images/partners&clients/partners/Network & communication/image010.png", alt: "Partner 10" },
      { src: "/images/partners&clients/partners/Network & communication/image014.png", alt: "Partner 14" },
      { src: "/images/partners&clients/partners/Network & communication/image015.png", alt: "Partner 15" },
      { src: "/images/partners&clients/partners/Network & communication/image016.png", alt: "Partner 16" },
      { src: "/images/partners&clients/partners/Network & communication/image020.png", alt: "Partner 20" },
      { src: "/images/partners&clients/partners/Network & communication/image021.png", alt: "Partner 21" },
      { src: "/images/partners&clients/partners/Network & communication/image022.png", alt: "Partner 22" },
      { src: "/images/partners&clients/partners/Network & communication/image026.png", alt: "Partner 26" },
      { src: "/images/partners&clients/partners/Network & communication/image027.png", alt: "Partner 27" },
      { src: "/images/partners&clients/partners/Network & communication/image028.png", alt: "Partner 28" },
      { src: "/images/partners&clients/partners/Network & communication/image032.png", alt: "Partner 32" },
      { src: "/images/partners&clients/partners/Network & communication/image033.png", alt: "Partner 33" },
      { src: "/images/partners&clients/partners/Network & communication/image034.png", alt: "Partner 34" },
      { src: "/images/partners&clients/partners/Network & communication/image038.png", alt: "Partner 38" },
      { src: "/images/partners&clients/partners/Network & communication/image039.png", alt: "Partner 39" },
      { src: "/images/partners&clients/partners/Network & communication/image040.png", alt: "Partner 40" },
      { src: "/images/partners&clients/partners/Network & communication/image044.png", alt: "Partner 44" },
      { src: "/images/partners&clients/partners/Network & communication/image045.png", alt: "Partner 45" },
      { src: "/images/partners&clients/partners/Network & communication/image046.png", alt: "Partner 46" },
      { src: "/images/partners&clients/partners/Network & communication/image050.png", alt: "Partner 50" },
      { src: "/images/partners&clients/partners/Network & communication/image051.png", alt: "Partner 51" },
      { src: "/images/partners&clients/partners/Network & communication/image052.png", alt: "Partner 52" },
      { src: "/images/partners&clients/partners/Network & communication/image056.png", alt: "Partner 56" },
      { src: "/images/partners&clients/partners/Network & communication/image058.png", alt: "Partner 58" },
      { src: "/images/partners&clients/partners/Network & communication/image060.png", alt: "Partner 60" },
      { src: "/images/partners&clients/partners/Network & communication/image062.png", alt: "Partner 62" },
      { src: "/images/partners&clients/partners/Network & communication/image063.png", alt: "Partner 63" },
      { src: "/images/partners&clients/partners/Network & communication/image064.png", alt: "Partner 64" },
      { src: "/images/partners&clients/partners/Network & communication/image068.png", alt: "Partner 68" },
      { src: "/images/partners&clients/partners/Network & communication/image069.png", alt: "Partner 69" },
      { src: "/images/partners&clients/partners/Network & communication/image070.png", alt: "Partner 70" }
    ]
  },
  {
    title: "Home Automation",
    logos: [
      { src: "/images/partners&clients/partners/Home Automation/image005.png", alt: "Partner 5" },
      { src: "/images/partners&clients/partners/Home Automation/image006.png", alt: "Partner 6" },
      { src: "/images/partners&clients/partners/Home Automation/image007.png", alt: "Partner 7" },
      { src: "/images/partners&clients/partners/Home Automation/image011.png", alt: "Partner 11" },
      { src: "/images/partners&clients/partners/Home Automation/image012.png", alt: "Partner 12" },
      { src: "/images/partners&clients/partners/Home Automation/image013.png", alt: "Partner 13" },
      { src: "/images/partners&clients/partners/Home Automation/image015.png", alt: "Partner 15" }
    ]
  }
];
